FROM docker.io/nadavker/fedora-43-base:latest

WORKDIR "/home"
RUN git clone https://github.com/NadavKeren/caffeine.git
RUN git clone https://github.com/NadavKeren/NSDI-Pipeline-Cache.git /home/artifact
WORKDIR "/home/caffeine"
RUN git checkout adaptive-pipeline-v1

RUN pip install xxhash

# FIRST COMPILATION
RUN ./gradlew compileJava

WORKDIR "/home/artifact"
RUN echo '{ "caffeine_root" : "/home/caffeine/", "resources" : "/home/traces/", "output" : "" , "results": "/home/results" }' > experiments/conf.json

COPY ./aliases.sh /home/aliases.sh
RUN echo 'source /home/aliases.sh' >> ~/.bashrc

ENTRYPOINT ["/bin/bash"]

CMD ["--login"]
